# Generated by Django 5.2.2 on 2025-08-16 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(verbose_name="Ім'я клієнта")),
                ('surname', models.CharField(verbose_name='Прізвище клієнта')),
                ('phone', models.CharField(unique=True, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=254, null=True, unique=True, verbose_name='Email')),
            ],
        ),
        migrations.CreateModel(
            name='Parcel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(unique=True, verbose_name='Номер посилки')),
                ('sender', models.CharField(verbose_name='Відправник')),
                ('recipient', models.CharField(verbose_name='Отримувач')),
                ('weight', models.FloatField(verbose_name='Вага')),
                ('status', models.CharField(verbose_name='Статус')),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Назва пункту')),
                ('adress', models.CharField(verbose_name='Адреса')),
                ('city', models.CharField(verbose_name='Місто')),
                ('width', models.FloatField(verbose_name='Ширина')),
                ('lenght', models.FloatField(verbose_name='Довжина')),
            ],
        ),
        migrations.CreateModel(
            name='Statuses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(verbose_name='Статус')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statuses', to='default.parcel')),
            ],
        ),
        migrations.CreateModel(
            name='ParcelStatusHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_edit', models.DateTimeField(auto_now_add=True, verbose_name='Час зміни статусу')),
                ('parcel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='default.parcel')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='default.statuses')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_history', to='default.warehouse')),
            ],
        ),
        migrations.AddField(
            model_name='parcel',
            name='warehouse',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcels', to='default.warehouse'),
        ),
    ]
