# Generated by Django 5.2.2 on 2025-08-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_alter_warehouse_lenght_alter_warehouse_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcelstatushistory',
            name='status',
            field=models.CharField(choices=[('Створено', 'created'), ('В дорозі', 'On the way'), ('Прибув до пункту видачі', 'Arrived at the pick-up point'), ('Видано', 'Issued')], verbose_name='Статус'),
        ),
        migrations.AlterModelOptions(
            name='client',
            options={'verbose_name': 'Клієнт', 'verbose_name_plural': 'Клієнти'},
        ),
        migrations.AlterModelOptions(
            name='parcel',
            options={'verbose_name': 'Посилка', 'verbose_name_plural': 'Посилки'},
        ),
        migrations.AlterModelOptions(
            name='parcelstatushistory',
            options={'verbose_name': 'Історія статусів посилки', 'verbose_name_plural': 'Історії статусів посилок'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Пункт видачі', 'verbose_name_plural': 'Пункти видачі'},
        ),
        migrations.DeleteModel(
            name='Statuses',
        ),
    ]
