# Generated by Django 5.2.2 on 2025-08-16 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_alter_parcelstatushistory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='status',
            field=models.CharField(choices=[('created', 'Створено'), ('on_way', 'В дорозі'), ('arrived', 'Прибув до пункту видачі'), ('issued', 'Видано')], default='created', verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='parcelstatushistory',
            name='status',
            field=models.CharField(choices=[('created', 'Створено'), ('on_way', 'В дорозі'), ('arrived', 'Прибув до пункту видачі'), ('issued', 'Видано')], verbose_name='Статус'),
        ),
    ]
