# Generated by Django 5.2.7 on 2025-12-18 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0002_basket_product_remove_school_persons_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=150, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
